### ISSUE TITLE
Enable Xdebug for Console Requests

### ISSUE THREAD

**Issue by bencroker** [nystudio107/plugindev#15]
The one thing I am missing is the ability to use Xdebug with console requests. According to the [Xdebug docs](https://xdebug.org/docs/step_debug), this is possible by running `export XDEBUG_SESSION=1`, but I believe only a cookie is being checked for in https://github.com/nystudio107/plugindev/blob/develop/docker-config/nginx/default.conf.

Would it be feasible to add a check for an environment variable? Then the following `make` command could be added, in addition to one for disabling Xdebug.

```
xdebug:
	docker exec -it -w $(PROJECT_DIR)$(CMS_DIR) $(CONTAINER) su-exec www-data /bin/sh -c 'export XDEBUG_SESSION=1'

**Comment by khalwat** [comment]
Yeah sure, I'm open to doing this! Whatever is the best way to handle it is fine with me.

Keep in mind though that queue jobs are run in a separate container (not sure if that matters for your purposes), so if you want XDebug to debug queue jobs you'll also need that.

Also if multiple containers are all running XDebug, what I _think_ will happen is they will each reach out to the IDE and you'll need to pick in the IDE which one to attach to. Haven't tested it tho.
