### ISSUE TITLE
Craft commands should not be run as the root/super user.

### ISSUE THREAD

**Issue by rostockahoi** [nystudio107/plugindev#2]
### Describe the bug
When running some composer scripts Craft says: "Craft commands should not be run as the root/super user." and points to a docs site: https://craftcms.com/knowledge-base/craft-console-root

However, there is the option to continue the script anyways.

Is this something to worry about? Is there even a non-root user in that Docker container?

### To reproduce
Steps to reproduce the behaviour:
1. Install plugindev and run for example `make composer post-craft-update`

### Expected behaviour
Composer script runs successfully

### Versions
- Craft version: 3.7.9

**Comment by khalwat** [comment]
It's fine in local dev, just put something like this in your `.env` file:

```
# Allow superuser in local dev
CRAFT_ALLOW_SUPERUSER=1
COMPOSER_ALLOW_SUPERUSER=1
```

Addressed in: https://github.com/nystudio107/plugindev/commit/e567adad03266bd2f68e1bc1b5c2d7bb7adb75ba
