### ISSUE TITLE
Postgres DB Seed not importing

### ISSUE THREAD

**Issue by pseudoclass** [nystudio107/plugindev#3]
### Describe the bug
When running the "make dev" command for the first time it seems the Postgres DB import is not occurring. After the initial setup and when trying to switch to Postgres via the "make postgres" command and refreshing the browser, the Install Craft page is displayed at the localhost:8000/admin URL.

I think this may be due to the postgres-db-seed file being a ZIP and not the uncompressed SQL file. I was able to remedy the problem by unzipping the SQL file in that directory and running the complete install process again. Don't know if this is a problem with my own local setup or not, but just wanted to add this report in case someone else is having the same problem.

### To reproduce
Steps to reproduce the behaviour:
1. Clear out Docker cache (to do a complete clean install)
2. Run "make dev"
3. When its ready visit localhost:8000/admin (default of MySQL works fine)
4. Run "make postgres" and refresh the browser
5. The Install Craft page comes up rather than the Craft Admin Login page

### Expected behaviour
Switching to "make postgres" should load Craft using the Postgres DB

### Versions
- Craft version: 3.7.26

**Comment by khalwat** [comment]
Good catch! It should have been in `.gz` format, not `.zip` format.

Fixed in https://github.com/nystudio107/plugindev/releases/tag/1.0.35

**Comment by pseudoclass** [comment]
Nice! Thanks for the update :)
