### ISSUE TITLE
Container naming in Makefile

### ISSUE THREAD

**Issue by rostockahoi** [nystudio107/plugindev#5]
I had to change the first line in Makefile from
`CONTAINER?=$(shell basename $(CURDIR))_php_1` to
`CONTAINER?=$(shell basename $(CURDIR))-php-1` to make make commands to work.

I remember some Docker changes regarding container naming but I don't know exactly.

Also I am not sure if this is a thing on my machine/my version of Docker.

Macbook M1, Docker version 20.10.12, build e91ed57

**Comment by khalwat** [comment]
Yeah this is a super annoying issue. Basically they changed it from _ to - in the v2 Docker Compose API, which they briefly made default. Now it's an option in Docker Desktop.

The rub is that any _existing_ container images will use whatever naming convention was in use when they were first created.

See here for details: https://stackoverflow.com/questions/69464001/docker-compose-container-name-use-dash-instead-of-underscore/70295720#70295720

I'll be changing the default to `-` and leaving it there, with my Docker Desktop set to the v2 Docker Composer API
